services:
    kasimi.logoutredirect.listener:
        class: kasimi\logoutredirect\event\listener
        arguments:
            - '@config'
            - '@request'
        tags:
            - { name: event.listener }
